@startuml Space-Invaders

class Juego
{
    -sonido:string
    -velocidad:int
    +Iniciar() 
    +Finalizar() 
}
class CampoBatalla{
    -colorfondo:string

}

class Jugador
{
    -vida:int
    -velocidad:int
    --Texto:string
    -Fuente:font
    +Morir()
    +Ganar()
    +Disparar()
    +Posicion()
    +QuitarVida()
    +Vivir()
    +Update()
    +UpdateVida()
    +Draw()
}

class NaveEspacial
{
    -PosX:int
    +MoverIzquierda()
    +MoverDerecha() 
    +Disparar() 
    +Destruir()

}

class Bala
{
    -posY:int
    -sprite:sprite
    +Posicion()
    +Update()
    +Matar()
    +Draw()

}

class Enemigo
{
    -point:vector2f
    -color:string
    -valor:int
    -estado:int
    -cadencia:int
    -timer:int
    -vida:int
    +Disparar()
    +Morir()
    +Aparecer()
    +ChangeDirection()
    +Posicion()
    +AumentarCadencia() 
    +Draw()
    +Update()


}

class Muro
{
    -estado:vector pair
    -color:string
    +Posicion()
    +Update()
    +Colision()
    +Draw()

     
}

class ObjetoDestructible
{
    +Destruir()
    -color::string
}

class Pantalla
{
    +Mostrar() 
    +Actualizar() 
}

class Menu{
    -color:string
    -fuente:font
    -texto:string
    +Mostrar()
    +Actualizar()
    +MoveUp()
    +MoveDown()
    +Draw()

}


Juego "1" *-- "1" Jugador
Juego "1" o-- "1" Pantalla
Juego "1" *-- "1" CampoBatalla
Juego "1" *-- "1" Menu
Jugador "1" o-- "1" NaveEspacial
Jugador "1" o-- "*" Bala
Juego "1" *-- "*" Enemigo
Juego "1" *-- "3" Muro

Enemigo "1" o-- "*" Bala


ObjetoDestructible <|-- Enemigo
ObjetoDestructible <|-- Bala
ObjetoDestructible <|-- Muro
ObjetoDestructible <|-- Jugador
Juego o-- CampoBatalla
CampoBatalla "1" o-- "*"ObjetoDestructible
CampoBatalla "1" o-- "3" Muro
ObjetoDestructible "*" --o "1" Pantalla
Menu "1" o-- "1" Pantalla


@enduml